# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: cobra-cli-template

builds:
  - id: cobra-cli-template
    main: ./main.go
    binary: cobra-cli-template
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X {{ .ModulePath }}/build_info.rawCLI_VERSION={{ .Version }}
      - -X {{ .ModulePath }}/build_info.rawBUILD_DATE={{ .Date }}
      - -X github.com/louiss0/g-tools/mode.buildMode=production

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: louiss0
    name: cobra-cli-template

winget:
  - name: cobra-cli-template
    publisher: the-code-fixer-23
    short_description: "Template for building Go CLIs with Cobra and Ginkgo."
    homepage: "https://github.com/louiss0/cobra-cli-template"
    license: MIT
    publisher_url: "https://github.com/louiss0"
    publisher_support_url: "https://github.com/louiss0/cobra-cli-template/issues/new"
    package_identifier: the-code-fixer-23.cobra-cli-template
    path: manifests/t/the-code-fixer-23/cobra-cli-template/{{ .Version }}
    commit_msg_template: "{{ .PackageIdentifier }}: {{ .Tag }}"
    release_notes: "{{.Changelog}}"
    repository:
      owner: louiss0
      name: winget-pkgs
      branch: "cobra-cli-template-{{ .Version }}"
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

homebrew_casks:
  - name: cobra-cli-template
    binaries:
      - cobra-cli-template
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/louiss0/cobra-cli-template"
    description: "Template for building Go CLIs with Cobra and Ginkgo."
    repository:
      owner: louiss0
      name: homebrew-the-code-fixer-23
      branch: main

nix:
  - name: cobra-cli-template
    commit_msg_template: "{{ .ProjectName }}: {{ .Tag }}"
    path: "pkgs/{{ .ProjectName }}/default.nix"
    homepage: "https://github.com/louiss0/cobra-cli-template"
    description: "Template for building Go CLIs with Cobra and Ginkgo."
    license: mit
    repository:
      owner: louiss0
      name: the-code-fixer-23-nur
      branch: main
